name: Deploy Images to GHCR

on:
  push:
    branches:
      - *

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Enshrouded Image'
        run: |
          sha_short="$(git rev-parse --short HEAD)"
          docker_image_repo="ghcr.io/tchupp/enshrouded"
          
          docker build . --tag "$docker_image_repo:$sha_short"
          docker tag "$docker_image_repo:$sha_short" "$docker_image_repo:latest" 
          docker push "$docker_image_repo:$sha_short"
          docker push "$docker_image_repo:latest"
